version: "1"

services:
  rabbitmq-1:
    build: .
    container_name: rabbit-1
    hostname: rabbit-host-1
    ports:
      - 5672:5672   # broker
      - 15672:15672 # management
      - 5552:5552   # streams
    expose:
      - 4369
      - 6000
      - 25672
      - 35672
      - 35677
      - 35682
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    environment:
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_ERLANG_COOKIE=erlang-cookie-must-be-same-on-all-nodes-123
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - rabbit-net
      - dbnet

networks:
  rabbit-net:
    name: rabbit-net
    driver: bridge
  dbnet:
    name: dbnet
    external: true